# This file contains vars used to configure the build system (build.py)
# Some values may be omitted, in this case the defaults are used

#build_dir: build
#changeset_dir: changeset

# directory where exercises are packed
exc_dir: exercises

# subdir inside `exc_dir` where howto images are put
img_subdir: img

# Path to Free-Exercise-DB Git submodule
# specified relative to build.py directory
freedb_dir: deps/free-exercise-db

# how each freedb data file will be named in excercise dirs
freedb_exc_json: data.json

# Model generation logic
freedb_model_gen:
  # Relative path (from freedb_dir) to JSON schema
  # Used to generate models
  schema_file: "{env.freedb_dir}/schema.json"

  # Path to generated model, relative to project dir
  model_file: models/freedb/base.py

  # Whether to update model checked-at field at build
  # for details see tools/genmodel.py
  renew_checked_at: false  # false reduces num of git changes

  # Extra keyword arguments passed to datamodel_codegen
  codegen_extras:
    output_model_type: 'pydantic_v2.BaseModel'




