# updated-at: 2025-03-21 00:11:43+00:00
# checked-at: 2025-03-21 00:11:43+00:00
# This file is autogenerated using tools/genmodel.py
# from free-exercise-db/schema.json
# 
from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, constr


class Force(Enum):
    NONE = None
    static = 'static'
    pull = 'pull'
    push = 'push'


class Level(Enum):
    beginner = 'beginner'
    intermediate = 'intermediate'
    expert = 'expert'


class Mechanic(Enum):
    isolation = 'isolation'
    compound = 'compound'
    NONE = None


class Equipment(Enum):
    NONE = None
    medicine_ball = 'medicine ball'
    dumbbell = 'dumbbell'
    body_only = 'body only'
    bands = 'bands'
    kettlebells = 'kettlebells'
    foam_roll = 'foam roll'
    cable = 'cable'
    machine = 'machine'
    barbell = 'barbell'
    exercise_ball = 'exercise ball'
    e_z_curl_bar = 'e-z curl bar'
    other = 'other'


class PrimaryMuscle(Enum):
    abdominals = 'abdominals'
    abductors = 'abductors'
    adductors = 'adductors'
    biceps = 'biceps'
    calves = 'calves'
    chest = 'chest'
    forearms = 'forearms'
    glutes = 'glutes'
    hamstrings = 'hamstrings'
    lats = 'lats'
    lower_back = 'lower back'
    middle_back = 'middle back'
    neck = 'neck'
    quadriceps = 'quadriceps'
    shoulders = 'shoulders'
    traps = 'traps'
    triceps = 'triceps'


class SecondaryMuscle(Enum):
    abdominals = 'abdominals'
    abductors = 'abductors'
    adductors = 'adductors'
    biceps = 'biceps'
    calves = 'calves'
    chest = 'chest'
    forearms = 'forearms'
    glutes = 'glutes'
    hamstrings = 'hamstrings'
    lats = 'lats'
    lower_back = 'lower back'
    middle_back = 'middle back'
    neck = 'neck'
    quadriceps = 'quadriceps'
    shoulders = 'shoulders'
    traps = 'traps'
    triceps = 'triceps'


class Category(Enum):
    powerlifting = 'powerlifting'
    strength = 'strength'
    stretching = 'stretching'
    cardio = 'cardio'
    olympic_weightlifting = 'olympic weightlifting'
    strongman = 'strongman'
    plyometrics = 'plyometrics'


class Model(BaseModel):
    id: constr(pattern=r'^[0-9a-zA-Z_-]+$')
    name: str
    force: Optional[Force] = None
    level: Level
    mechanic: Optional[Mechanic]
    equipment: Optional[Equipment]
    primaryMuscles: List[PrimaryMuscle]
    secondaryMuscles: List[SecondaryMuscle]
    instructions: List[str]
    category: Category
    images: List[str]
